
default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  username: patato
  password: 123456
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: test_psql

test:
  <<: *default
  database: NewTest_test

#   production:
#     url: <%= ENV['DATABASE_URL'] %>

